### ISSUE TITLE
Just wanted to say thanks!

### ISSUE THREAD

**Issue by dan-v** [lukaspieper/Gcam-Services-Provider#1]
Thanks for building this! I was planning on doing this exact same thing, as I really had no reason to run microg core besides google camera.

**Comment by LumenReaper** [comment]
Thanks for reaching out. I'm glad you like it. 

That's exactly why I developed this, the newer microg releases have side effects on other apps and the older ones that worked for my setup might still have other problems. 

This solution here is simply minimalistic for this one task and works without any permissions.

**Comment by renlord** [comment]
Same, thank you for this. Its a very clean and simple implementation also.

**Comment by boniek83** [comment]
Thank you!

**Comment by lukaspieper** [comment]
> Same, thank you for this. Its a very clean and simple implementation also.

I'm sorry, I somehow missed to reply. It was just possible to keep the implementation simple, because Gcam does not insert values. 

> Thank you!

Your welcome, thanks for reaching out.

**Comment by fabianski7** [comment]
I'd like to thank you too, I just found your app!

I was using the microg with blocked internet connection. It was a workaround that worked but bothered me.

You could create a more detailed readme about the app, its permissions, license, the differences between the microg and other useful information.  

Do you have any plans to add to any repository? like F-droid or IzzyOnDroid

**Comment by beerisgood** [comment]
I wonder if this can be implemented in GrapheneOS?
@renlord

**Comment by lukaspieper** [comment]
> I'd like to thank you too, I just found your app!

Your welcome.

> You could create a more detailed readme about the app, its permissions, license, the differences between the microg and other useful information.

I have updated the readme. If you still miss something, do not hesitate to reach out again.

> Do you have any plans to add to any repository? like F-droid or IzzyOnDroid

Since this is a very small application with a [limited lifetime (at least on GOS)](https://github.com/GrapheneOS/os_issue_tracker/issues/255), I did not intend to make this app available in any F-Droid repository. In my opinion, F-Droid is already full enough with apps that are no longer maintained.

> I wonder if this can be implemented in GrapheneOS?

Please have a look at this [issue](https://github.com/GrapheneOS/os_issue_tracker/issues/204).

**Comment by Atrate** [comment]
I rarely do this, but this app is exactly what I needed for the past 2 years, thank you so much!

**Comment by lukaspieper** [comment]
> I rarely do this, but this app is exactly what I needed for the past 2 years, thank you so much!

Glad you like it.

@fabianski7 Just found out that this app was added to IzzyOnDroid's F-Droid repository.

**Comment by beerisgood** [comment]
> @fabianski7 Just found out that this app was added to IzzyOnDroid's F-Droid repository.

But this isn't from you right? 
https://github.com/lukaspieper/Gcam-Services-Provider/issues/2

**Comment by lukaspieper** [comment]
> But this isn't from you right?
> #2

What does the "this" refer to? The app? The repository? 

According to the information [here](https://android.izzysoft.de/repo/info), the IzzyOnDroid repository consists of the binaries (apks) provided by the developers. Therefor, it should be the same apk that I have provided in the release section.

Your question here has nothing to do with issue #2, because there you ask for the official F-Droid repository, where my app is not available.

If I still couldn't answer your questions to your satisfaction, please ask your questions in more detail.

**Comment by IceWreck** [comment]
Thanks a lot @lukaspieper 
Works perfectly

**Comment by thelittlefireman** [comment]
Thanks @lukaspieper 
Just what i need :+1:  :)

**Comment by lukaspieper** [comment]
Hello everyone,

I would like to thank you all for your feedback and support. Unbelievable that you have given this project, which practically consists of one class and a little configuration, over 100 stars. If I had known that so many people would be using my little app, I would have given it a less bulky name 😆 

I have activated the new GitHub feature "Discussions". My idea is to use that feature as an easy way to talk about compatibility, changes to Gcam, etc. Any feedback and questions should also be better served there, so I'll close this issue.

Again many thanks for the positive feedback.
