### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by rugk** [lukaspieper/Gcam-Services-Provider#34]
It would be great to see this Android app on F-Droid!

[F-Droid](https://f-droid.org/) is an Android app store specifically for free/libre open-source apps. It would be great if your app could be released there, as it is the number one for getting FLOSS Android apps for many people.
F-Droid also builds all apps from source ([optionally even reproducible](https://f-droid.org/en/docs/Reproducible_Builds/)), so downloads from there can be trusted.

The [app developer FAQ](https://f-droid.org/en/docs/FAQ_-_App_Developers/) or [the quick start guide](https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide/) may help you to get started.

BTW a release on F-Droid could also bring some (more) popularity (in case that is intended), as it will show up in the app (new apps are featured there).

**Comment by lukaspieper** [comment]
Hi,

I think this topic has been discussed elsewhere in the issues. Personally, I still don't think it's a good idea, as the future of this application is highly uncertain (see current compatibility restrictions). Nevertheless, this is free software, which means you can also bring this app into the F-Droid Store without my participation.

For me personally to consider listing it in the F-Droid Store, the following points would need to be clarified/addressed.

1. Can F-Droid install the app with the required installation flag (`--force-queryable`)?
2. In order to inform users at some point, it would be necessary to implement issue #29. Otherwise, the user is missing the most necessary information.
3. The app would then need some kind of logo, doesn't have to be anything fancy, but the placeholder has to go.

**Comment by Iey4iej3** [comment]
> Nevertheless, this is free software, which means you can also bring this app into the F-Droid Store without my participation.

This seems impossible without a fork. The OP might also open an issue at https://gitlab.com/fdroid/rfp/-/issues

**Comment by b3pio** [comment]
>     3. The app would then need some kind of logo, doesn't have to be anything fancy, but the placeholder has to go.
>

You can use this logo I quickly put together if you'd like
![gcam-services](https://user-images.githubusercontent.com/59568034/143068585-214abb7a-94e4-4478-afe6-61dd64b30eab.png)

**Comment by rugk** [comment]
Maybe provide the SVG(?) or so sources too, so it can be adjusted if needed… :upside_down_face:

**Comment by lukaspieper** [comment]
Thank you very much for your contribution @b3pio. I like it very much. The image as a vector graphic would be great. 

Since I don't have much time at the moment, it would be helpful if someone could sort out point 4.
> How to handle the two different APKs in F-Droid?

Thank you.

**Comment by Iey4iej3** [comment]
> Since I don't have much time at the moment

You could simply open a thread in https://gitlab.com/fdroid/rfp/-/issues and wait for their responses, I think.

**Comment by b3pio** [comment]
[gcam-services-logo.zip](https://github.com/lukaspieper/Gcam-Services-Provider/files/7605178/gcam-services-logo.zip)
@lukaspieper @rugk SVG logo file inside zip, enjoy 😃

**Comment by lukaspieper** [comment]
@b3pio Thanks for the SVG.

I opend the issue: https://gitlab.com/fdroid/rfp/-/issues/1932

**Comment by lukaspieper** [comment]
The basic variant is now on F-Droid ([link](https://www.f-droid.org/de/packages/de.lukaspieper.gcam.services/)). 

Since the inclusion of new apps and the further updates require both manpower and computing power, I'll leave this here: https://www.f-droid.org/de/donate/
