### ISSUE TITLE
GCam 8.4 won't launch

### ISSUE THREAD

**Issue by lbdroid** [lukaspieper/Gcam-Services-Provider#64]
**Describe the bug**
Logcat excerpt:
GooglePlayServicesUtil: com.google.android.GoogleCamera requires the Google Play Store, but it is missing.

I've tried "fakestore" -- it isn't recognized.

**Comment by lukaspieper** [comment]
Hi,

please update this issue to match [the issue template](https://github.com/lukaspieper/Gcam-Services-Provider/blob/ee52c706b54d9e2ca2545df2d5ab5e25b586fe78/.github/ISSUE_TEMPLATE/bug-or-crash-report.md).

Thanks!

**Comment by lukaspieper** [comment]
Closing this issue now as OP does not seem to be interested in finding a solution together. Can be reopened when further information are provided.

**Comment by lbdroid** [comment]
Issue reported was clear, your demand for reformatting according to a "template" was hostile and shows a serious lack of interest in actually working on this, therefore not worth my effort to engage with you on this or any other topics.

**Comment by lukaspieper** [comment]
I clearly disagree with you here. 

I use Gcam 8.4.300.414775575.18 with the latest GrapheneOS and my app and it works fine. 

You exclusively told that you have problems with **some** Gcam version 8.4 and you cut a line from the log where you think that is the problem. I can't help you on that basis.

If you look at other interactions of me with users, you should notice that I answer in detail and always try to find the best solution for the user and accordingly recommend other apps if they are better in that use case.

**Comment by thestinger** [comment]
The official approach recommended by GrapheneOS is installing the official GSF and Google Camera apps. Those can simply be installed as regular apps via the standard installation UI. Google Camera doesn't require Play services (GMS). GSF doesn't need to be granted any access and is simply another regular sandboxed app like Google Camera. If necessary we can make this clearer on our site.

**Comment by thestinger** [comment]
This GSF substitute still works fine for that specific use case when installed with forceQueryable enabled via ADB but ADB is not recommended for production use. It's simpler to use the official GSF app and sandboxed Play services sets up forceQueryable for it automatically. The official GSF will get any apps that depend on GSF alone working which is a lot more than Google Camera. It's simply infrastructure and the actual services, etc. are in GMS, which is also supported, but not needed for Google Camera.

**Comment by lukaspieper** [comment]
I have no problem with your first comment and you are also welcome to continue commenting in this project. I just wanted to express with the reference to the README that I do not hide your alternative or consider it as competition.

Currently my app still has the advantage that the preview button in Gcam works with it, which installing GSF does not do to my knowledge. As long as this is the case, there is still a good reason for some GrapheneOS users to prefer my app.

I added `android:forceQueryable` a long time ago, but after an OS update this had no effect anymore. That it works again without ADB is due to [this intent](https://github.com/lukaspieper/Gcam-Services-Provider/blob/2f66fe389d3550b23aebce024f2547f489156d21/app/src/main/AndroidManifest.xml#L44).

What I wonder, though, is why you want to help the OP. He only told the rough Gcam version and copied a line from the log. How do you know that he is using GrapheneOS at all?

**Comment by thestinger** [comment]
> What I wonder, though, is why you want to help the OP. He only told the rough Gcam version and copied a line from the log. How do you know that he is using GrapheneOS at all?

I checked their history because of their activity on the GrapheneOS issue tracker. I was trying to help them in order to attempt to resolve them seemingly being mad at us diplomatically.

**Comment by lbdroid** [comment]
This bug has nothing to do with graphene. I started using graphene well after this. I no longer care about gcam, since the graphene camera application works extremely well and is, unlike any other open source camera application, able to zoom out to less than 1.0.
