### ISSUE TITLE
can you make same for youtube vanced ?

### ISSUE THREAD

**Issue by bingoxo** [lukaspieper/Gcam-Services-Provider#82]
youtube vanced requires a custom microg to work , is there a way to fake that dependency like with gcam ?

unfortunately vanced has been discontinued but the app still works , you can get the apks in https://github.com/Norikiru/VancedAPKs/releases/tag/yt-v17 or https://github.com/cuynu/ytvanced

(i know about newpipe but i prefer yv)

**Comment by lukaspieper** [comment]
Hi,

I'm sorry but beside that your request is outside the scope of this project, I personally don't understand why any developer would start spending his free time to implement a stub service for an app that is somewhere between discontinued and soon deprecated (assuming that the stub implementation is technically possible).

I brought up this stub service because at that time there was no good alternative to Google Camera. Today GrapheneOS' Camera is a valid competitor.
